// Varieties hidden from the selector (battle-only, cosmetic duplicates, etc.)
export const hidden = [
  '-totem',
  '-busted',
  '-noice',
  '-rock-star',
  '-belle',
  '-phd',
  '-pop-star',
  '-libre',
  '-cosplay',
  '-cap',
  '-starter',
  '-droopy',
  '-stretchy',
  '-power-construct',
  '-resolute',
  '-orange',
  '-yellow',
  '-green',
  'minior-blue',
  '-indigo',
  '-violet',
  'magearna-original',
  '-gulping',
  '-gorging',
  '-dada',
  '-family-of-three',
  '-blue-plumage',
  '-yellow-plumage',
  '-white-plumage',
  '-three-segment',
  '-roaming',
  '-own-tempo',
  '-mega-z'
];

// Maps variety name patterns to French display names (primary label)
export const varietyMap: Record<string, string> = {
  '-alola': 'Alola',
  '-galar': 'Galar',
  '-hisui': 'Hisui',
  'tauros-paldea-combat': 'Race Combative',
  'tauros-paldea-blaze': 'Race Flamboyante',
  'tauros-paldea-aqua': 'Race Aquatique',
  '-paldea': 'Paldea',
  '-single-strike': 'Poing Final',
  '-rapid-strike': 'Mille Poings',
  '-unbound': 'Déchaîné',
  '-incarnate': 'Avatar',
  '-therian': 'Totémique',
  '-midday': 'Diurne',
  '-midnight': 'Nocturne',
  'lycanroc-dusk': 'Crépusculaire',
  '-ice': 'Cavalier du Froid',
  'calyrex-shadow': 'Cavalier d\'Effroi',
  '-altered': 'Alternative',
  '-origin': 'Originelle',
  '-land': 'Terrestre',
  '-sky': 'Céleste',
  'necrozma-dusk': 'Crinière du Couchant',
  '-dawn': 'Ailes de l\'Aurore',
  '-ultra': 'Ultra',
  '-zero': 'Zéro',
  '-hero': 'Héros',
  '-solo': 'Solitaire',
  '-school': 'Banc',
  '-terastal': 'Téracristal',
  '-stellar': 'Stellaire',
  '-heat': 'Chaleur',
  '-frost': 'Froid',
  '-fan': 'Hélice',
  '-mow': 'Tondeuse',
  '-wash': 'Lavage',
  '-bloodmoon': 'Lune vermeille',
  '-small': 'Mini',
  '-large': 'Maxi',
  '-super': 'Ultra',
  '-eternamax': 'Infinimax',
  '-attack': 'Attaque',
  '-defense': 'Défense',
  '-speed': 'Vitesse',
  '-battle-bond': 'Synergie',
  '-ash': 'Sacha',
  '-sunny': 'Solaire',
  '-rainy': 'Eau de Pluie',
  '-snowy': 'Blizzard',
  '-full-belly': 'Rassasié',
  '-hangry': 'Affamé',
  '-black': 'Noir',
  '-white': 'Blanc',
  '-amped': 'Aiguë',
  '-low-key': 'Grave',
  '-male': 'Mâle',
  '-female': 'Femelle',
  '-crowned': 'Couronné',
  '-wellspring-mask': 'Masque du Puits',
  '-hearthflame-mask': 'Masque du Fourneau',
  '-cornerstone-mask': 'Masque de Pierre',
  '-aria': 'Chant',
  '-pirouette': 'Danse',
  '-50': '50%',
  '-complete': 'Parfait',
  '-10': '10%',
  '-plant': 'Cape Plante',
  '-sandy': 'Cape Sable',
  '-trash': 'Cape Déchet',
  '-red-striped': 'Rouge',
  '-blue-striped': 'Bleu',
  '-white-striped': 'Blanc',
  '-eternal': 'Fleur éternelle',
  '-shield': 'Bouclier',
  '-blade': 'Epée',
  '-baile': 'Flamenco',
  '-pom-pom': 'Pom-Pom',
  '-pau': 'Hula',
  '-sensu': 'Buyō',
  '-red-meteor': 'Météore',
  'minior-red': 'Noyau'
};

// Maps suffix patterns appended to the primary label
export const appendVarietyMap: Record<string, string> = {
  '-gmax': 'Gigamax',
  '-mega': 'Méga',
  '-zen': 'Zen',
  '-x': 'X',
  '-y': 'Y',
  '-z': 'Z',
  '-primal': 'Primal'
};

// Pokémon whose battle-only forms are not PokeAPI varieties but are worth exposing
// as selectable forms in the sheet. These forms share the same stats/types/ability
// as the base form — only the sprite changes.
export const formVarieties: Record<string, { formName: string, title: string }[]> = {
  'cherrim': [{ formName: 'cherrim-sunshine', title: 'Soleil' }],
  'shellos': [{ formName: 'shellos-east', title: 'Mer Est' }],
  'gastrodon': [{ formName: 'gastrodon-east', title: 'Mer Est' }],
};
