/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetIcon: typeof import('./components/AssetIcon.vue')['default']
    BattleMap: typeof import('./components/BattleMap.vue')['default']
    BattleMapTile: typeof import('./components/BattleMapTile.vue')['default']
    CharacterIcon: typeof import('./components/CharacterIcon.vue')['default']
    ConfirmCancelDialog: typeof import('./components/ConfirmCancelDialog.vue')['default']
    DiceRoll: typeof import('./components/DiceRoll.vue')['default']
    EncounterFilters: typeof import('./components/EncounterFilters.vue')['default']
    PokemonSheet: typeof import('./components/PokemonSheet.vue')['default']
    PokemonSheetAttacks: typeof import('./components/PokemonSheetAttacks.vue')['default']
    PokemonSheetExperience: typeof import('./components/PokemonSheetExperience.vue')['default']
    PokemonSheetHeader: typeof import('./components/PokemonSheetHeader.vue')['default']
    PokemonSheetInventory: typeof import('./components/PokemonSheetInventory.vue')['default']
    PokemonSheetIQSkills: typeof import('./components/PokemonSheetIQSkills.vue')['default']
    PokemonSheetSpecificities: typeof import('./components/PokemonSheetSpecificities.vue')['default']
    PokemonSheetStats: typeof import('./components/PokemonSheetStats.vue')['default']
    PokemonSheetTalents: typeof import('./components/PokemonSheetTalents.vue')['default']
    RandomItemCard: typeof import('./components/RandomItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeImage: typeof import('./components/TypeImage.vue')['default']
  }
}
