/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetIcon: typeof import('./components/AssetIcon.vue')['default']
    BattleMap: typeof import('./components/BattleMap.vue')['default']
    BattleMapTile: typeof import('./components/BattleMapTile.vue')['default']
    CharacterIcon: typeof import('./components/CharacterIcon.vue')['default']
    ConfirmCancelDialog: typeof import('./components/ConfirmCancelDialog.vue')['default']
    EncounterFilters: typeof import('./components/EncounterFilters.vue')['default']
    PokemonSheet: typeof import('./components/PokemonSheet.vue')['default']
    RandomItemCard: typeof import('./components/RandomItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeImage: typeof import('./components/TypeImage.vue')['default']
  }
}
