/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetIcon: typeof import('./components/AssetIcon.vue')['default']
    BattleMap: typeof import('./components/BattleMap.vue')['default']
    BattleMapTile: typeof import('./components/BattleMapTile.vue')['default']
    CharacterIcon: typeof import('./components/CharacterIcon.vue')['default']
    ConfirmCancelDialog: typeof import('./components/ConfirmCancelDialog.vue')['default']
    EncounterFilters: typeof import('./components/EncounterFilters.vue')['default']
    PokemonSheet: typeof import('./components/PokemonSheet/PokemonSheet.vue')['default']
    PokemonSheetAttacks: typeof import('./components/PokemonSheet/PokemonSheetAttacks.vue')['default']
    PokemonSheetExperience: typeof import('./components/PokemonSheet/PokemonSheetExperience.vue')['default']
    PokemonSheetHeader: typeof import('./components/PokemonSheet/PokemonSheetHeader/PokemonSheetHeader.vue')['default']
    PokemonSheetHeaderMd: typeof import('./components/PokemonSheet/PokemonSheetHeader/PokemonSheetHeaderMd.vue')['default']
    PokemonSheetHeaderSm: typeof import('./components/PokemonSheet/PokemonSheetHeader/PokemonSheetHeaderSm.vue')['default']
    PokemonSheetHeaderXs: typeof import('./components/PokemonSheet/PokemonSheetHeader/PokemonSheetHeaderXs.vue')['default']
    PokemonSheetInventory: typeof import('./components/PokemonSheet/PokemonSheetInventory.vue')['default']
    PokemonSheetIQSkills: typeof import('./components/PokemonSheet/PokemonSheetIQSkills.vue')['default']
    PokemonSheetSpecificities: typeof import('./components/PokemonSheet/PokemonSheetSpecificities.vue')['default']
    PokemonSheetStats: typeof import('./components/PokemonSheet/PokemonSheetStats.vue')['default']
    PokemonSheetTalents: typeof import('./components/PokemonSheet/PokemonSheetTalents.vue')['default']
    RandomItemCard: typeof import('./components/RandomItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypeImage: typeof import('./components/TypeImage.vue')['default']
  }
}
